### ISSUE TITLE
When creating 3D geometries using revolve/sweep, the rainbow color rendering is kind of broken

### ISSUE THREAD

**Issue by billynew** [jeb482/SparrowHawk#3]
with surface triangle normal set wrong (I assume).

Maybe start by checking "public static bool addSceneNode" function?

**Comment by billynew** [comment]
Or sth to do with "RGBNormalMaterial"?

**Comment by jeb482** [comment]
Could you add a screenshot?

**Comment by billynew** [comment]
![image](https://user-images.githubusercontent.com/1237408/46174351-c7ded880-c276-11e8-848d-c97bbf8d9e7c.png)

**Comment by jeb482** [comment]
I wo der if this would be solved by turning on Backface culling. Looks like a z-fighting issue on the generated mesh. We'd have to be careful because turning on culling whole-sale would mess up the marking menu.

**Comment by billynew** [comment]
The write color rendering (i.e. when the model is confirmed for printing) doesn't seem to have the same issue though. Maybe here is what we can do-> use backface culling to see if the rendering is correct first. if so we will decide if we really want to fix the conflict with the marking menu or just keep it like this. The rendering issue is not *critical* so fixing could be optional

**Comment by jeb482** [comment]
Fixed in c58a42b3ede9c3734aeb94322b8341d8307e6d45.
