### ISSUE TITLE
Where is the code to change the rendering alpha? 

### ISSUE THREAD

**Issue by billynew** [jeb482/SparrowHawk#5]
![image](https://user-images.githubusercontent.com/1237408/46447223-9ff7e500-c74e-11e8-911a-2a0af4dc4af8.png)

**Comment by jeb482** [comment]
Changed global mAlpha to 1 (line 23 of RGBNormalMaterial.cs) in faef945aa59e4d9fa505b11fff1593b6ad066cf5.

**Comment by billynew** [comment]
This simple change makes it look a lot better... previously the snap points cannot be seen if blocked by the RGB rendering surface...
